name: 需求提交
description: 新增需求.
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        - 避免通用或模糊的标题，例如“新增某些东西”或“几个问题”——尽可能具有描述性。
        - 让你的问题集中在一个需求上。如果您有多个需求报告，请为每个需求报告创建一个单独的问题。
        - 问题应该代表**完整且可操作的**工作项目。如果您对某事不确定或有疑问，请开始[讨论](https://github.com/xisuo67/XHS-Spider/discussions/new)。

        ___

  - type: input
    attributes:
      label: 版本
      description: 新增需求期望在哪个版本上发布？（历史版本不会新增需求也不在维护）。
      placeholder: v1.0.0.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: 需求描述
      description: >
        请详细描述你的需求，例如采集url，新增导出excel功能，是否增加设置，你期望的实现方式等
      placeholder: |
        笔记 URL: ...

        系统设置:
        - ...

        步骤:
        - 步骤 1
        - 步骤 2
        - 步骤 3
    validations:
      required: true

  - type: textarea
    attributes:
      label: 细节
      description: 对需求进行清晰、彻底的解释，包括您可能认为相关的任何其他信息。
      placeholder: |
        - 预期行为: ...
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Checklist
      description: 快速检查列表，以确保一切正常。
      options:
        - label: 我已经查看了现有问题以确保之前没有报告过此需求
          required: true
        - label: 我已经为这个问题提供了一个描述性标题
          required: true
        - label: 我已确保该需求具有通用性
          required: true
        - label: 我已经提供了尽可能有效地描述该需求所需的所有信息 
          required: true
        - label: 我赞助了这个项目
          required: false

  - type: markdown
    attributes:
      value: |
        如果您正在努力提供可行性需求，或者如果其他原因阻止您创建完整的需求报告，请改为开始[讨论](https://github.com/xisuo67/XHS-Spider/discussions/new)